# Generated by Django 4.2.1 on 2023-06-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_name_skill_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='url',
            field=models.CharField(default='.jpg'),
        ),
        migrations.AddField(
            model_name='skill',
            name='isOngoing',
            field=models.BooleanField(default=False),
        ),
    ]
