# Generated by Django 4.2.1 on 2023-06-05 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_file_url_skill_isongoing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
    ]
