# Generated by Django 4.2.1 on 2023-06-07 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_review_contentblock_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='contentBlock',
        ),
        migrations.RemoveField(
            model_name='review',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='review',
            name='post',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
