# Generated by Django 4.2.1 on 2023-06-07 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_remove_review_contentblock_remove_review_creator_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
