# Generated by Django 4.2.1 on 2023-06-07 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='contentBlock',
            new_name='content',
        ),
    ]
