# Generated by Django 4.2.1 on 2023-06-07 02:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0018_alter_post_rating_alter_post_savedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='savedBy',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
